before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: jF8TO986eH8zfxjLzkC3TcMGkdjPK2zhLyv5ntSRy5gwr3SZ6jkgs4N/ZIPb+gQPWH+UMg4lW90wPQE3zSWGWFgAtf0Rdpj5HAuJHuqUOgYorJBF4aiAYJ8gQWgDWjLv5Z2DTDzjkJvaTWcd8vcDiN3uEIkHg7K3Z6qX7tEBE2yxJtGIyDazKTp3zcuZsG8eFh1dkKzxzRr89FbTxM6JhiQphqOjYcPdR+lrb7IBW+NY0r5fyWu9tFgG8NnbObaUsnBsCLXcq3U4qBfw3pJTDugf2CGFXtO90jWXxCQyMdj/f4T1Kik9NPx7b1bnfQ1pP9SH0j6uGgju7Qbz6jwzCiV2Bw5uK1+nVffVJaq0qnQwZKGoRky4tubH/BwJL1LynaL7CEAJjuop9p1TOmwhXeh6gAxVn9GL/uOXZhF8xtr9NuS+f0QxVXFqIVwnwJa5ljgSTaHP18dEeCAflng5JjcHcUqKqWc23H5Smdz0R3EkO4eADRtbBPF455YeyFNPg+8GqyG849GtmVmtOtdp18ptKy3ix/QwzgLdWpWHD4ws1e8Mafsi0CBMTANgxIfO6Fap16z4mCOgGGkSZz1E2i2FoyEj+JG2IaOC0KzlqHIdVIsYOTvG1j1nnS83lxPngJQYquzhKsCb6/VhBkqTQMqnqUAsjZU0QQDHNZYyttc=
